### ISSUE TITLE
Dar soporte a las fases del procesado en DevelopmentPlatform

### ISSUE THREAD

**Issue by DavidGonzalezLopez** [AdrianArnaiz/GESPRO_PracticaGestionTareas_1718#35]

**Comment by AdrianArnaiz** [comment]
Plataforma desarrollada. Catacterísticas:

Cargar vídeo con FileChooser.
Reproductor de vídeo con controles.
Una pestaña por fase con controles de los parámetros de los diferentes algoritmos.
Permite realizar modificaciones de los parámetros en tiempo real.
TAREA ACABADA
