### ISSUE TITLE
Preprocesado

### ISSUE THREAD

**Issue by RodrigoBarandaCastrillo** [AdrianArnaiz/GESPRO_PracticaGestionTareas_1718#37]
Investigar que algoritmos se pueden aplicar antes de la extracción de fondo para mejorar sus resultados.

**Comment by DavidGonzalezLopez** [comment]
Se obtienen mejores resultados realizando los siguientes pasos:

Conversión a escala de grises (mejora eficiencia).
Ecualización del historiograma (mejora contraste).
Desenfoque gausiano (reduce ruido).
Las tres fases han sido implementadas en la DevelopmentPlatform.
