### ISSUE TITLE
Desarrollar herramienta para conteo manual

### ISSUE THREAD

**Issue by AdrianArnaiz** [AdrianArnaiz/GESPRO_PracticaGestionTareas_1718#58]
Desarrollar una herramienta que permita contabilizar las abejas que hay en cada determinado frame de un vídeo. Los resultados se guardarán en un CSV.

**Comment by DavidGonzalezLopez** [comment]
Se ha desarrollado una app en java que permite el conteo manual de abejas de un conjunto de frames de forma fácil. Simplemente se debe hacer click en cada abeja del frame y la app se encarga de realizar el conteo y finalmente generar un archivo numBees.txt con los resultados.

Source code: CountingPlatform
Ejecutable: CountingPlatform.v1.jar
